### ISSUE TITLE
Add new metrics on the Summary Page

### ISSUE THREAD

**Issue by dyegowermelinger** [Farfetch/maestro#183]
## Description

Add new metrics on the Summary Page, like the ones shown on the image.

<img width="1202" alt="Screenshot 2022-02-04 at 17 25 28" src="https://user-images.githubusercontent.com/37643825/152574530-ab8c07b3-2425-4b21-9388-5037c4f5e2c5.png">

**Comment by vitaliimelnychuk** [comment]
https://ant.design/components/table/#components-table-demo-summary
https://ant.design/components/table/#components-table-demo-fixed-columns 

I think, there are a few ways of how we could do this

- have fixed columns and scroll for it. 
- add configuration on top with a list of columns we want to see on the table and only then enable scroll if needed.

**Comment by vitaliimelnychuk** [comment]
Great job guys 😄 🚀
