### ISSUE TITLE
Disable `simple data writer` plugin before test execution

### ISSUE THREAD

**Issue by nunodio** [Farfetch/maestro#205]
## Description
Develop a solution to disable the `Simple data plugin` from the test plans when the` backend listener mode` is active.

## Solution
Manipulate the JMX file before text execution in order to disable `Simple Data Writer` plugin.
We can disable the plugin by setting `enabled="false"` on all the instances of `ResultCollector guiclass="SimpleDataWriter"`

Example:
```
<ResultCollector guiclass="SimpleDataWriter" testclass="ResultCollector" testname="Simple Data Writer" enabled="false">
```

**Comment by vitaliimelnychuk** [comment]
I think we could also add more plugins that could be disabled that are related to listeners since they only can be used from Jmeter UI and directly effect the performance of test execution.

**Comment by crazyplayy** [comment]
Plugin no longer used
