### ISSUE TITLE
Delete the Test Configuration

### ISSUE THREAD

**Issue by dyegowermelinger** [Farfetch/maestro#263]
## Description

I should be able to delete a test plan and hide the test from the list.

## Possible Solution

Create a logical delete for the test plan.

- Create a delete button on the Test Configuration Page
- Show the Run dependencies of this test (#265)
- Only allows if there is no Run dependency to delete
- Remove the Test Configuration

**Comment by vitaliimelnychuk** [comment]
@dyegowermelinger Do you mean to remove `Run` from History?

We have also `RunPlan` as a part of `TestConfiguration` that basically represents JMeter execution plan.
