### ISSUE TITLE
Showing Agents deleted as Available

### ISSUE THREAD

**Issue by dyegowermelinger** [Farfetch/maestro#384]
## Expected behavior
After deleting one machine not show it on the **Agents Page**

## Actual behavior
Showing machines that were deleted with the status Available
<img width="1234" alt="Screenshot 2022-05-16 at 10 26 16" src="https://user-images.githubusercontent.com/37643825/168562615-e839132b-560e-4bc1-b0e6-22c6daab83b5.png">

## Steps to reproduce

1. Create an agent
2. Check the agent on the Agent Page
3. Delete the agent machine
4. The agent will be shown on the Agent Page

**Comment by vitaliimelnychuk** [comment]
It's probably because the scheduler was not started. 

Another thing that we could have here is to delete agents manually in the case they are not needed.
